# Generated by Django 4.1.3 on 2023-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TestObject',
        ),
    ]
