# Generated by Django 4.1.3 on 2023-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wflow', '0003_alter_house_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='total_expenses',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
