# Generated by Django 4.1.3 on 2023-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wflow', '0004_house_total_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('SFH', 'Single-Family Home'), ('SDH', 'Semi-Detached Home'), ('MFH', 'Multifamily Home'), ('APA', 'Apartment'), ('CON', 'Condominium'), ('COP', 'Co-Op'), ('TIN', 'Tiny Home'), ('MAN', 'Manufactured Home')], default='APA', max_length=3),
            preserve_default=False,
        ),
    ]
