# Generated by Django 4.1.3 on 2023-03-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wflow', '0007_rename_total_expenses_house_future_total_gas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='future_total_gas',
        ),
        migrations.RemoveField(
            model_name='house',
            name='future_total_liters',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_gas',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_liters',
        ),
    ]
