# Generated by Django 4.1.3 on 2023-03-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_alter_device_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='SensorTypeDefinition',
            fields=[
                ('sensor_type', models.CharField(choices=[('FLO', 'Flow Sensor'), ('LEV', 'Water Level'), ('HEA', 'Water Heater')], max_length=3, primary_key=True, serialize=False)),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('values', models.JSONField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensortypedefinition'),
        ),
    ]
