# Generated by Django 4.1.3 on 2023-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortypedefinition',
            name='sensor_type',
            field=models.CharField(choices=[('FLO', 'Flow Sensor'), ('LEV', 'Water Level'), ('HEA', 'Water Heater'), ('SAC', 'Shower Actuator'), ('HAC', 'Heater Actuator')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
