# Generated by Django 4.1.3 on 2023-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fanily_members',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('SIN', 'Single'), ('REL', 'In a relationship'), ('ENG', 'Engaged'), ('MAR', 'Married')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, choices=[('EMP', 'Employee'), ('UNE', 'Unemployed'), ('STU', 'Student'), ('RET', 'Retired'), ('ENT', 'Entepreneur'), ('FRE', 'Freelancer')], default=None, max_length=3, null=True),
        ),
    ]
