# Generated by Django 4.1.3 on 2023-02-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_fanily_members_customuser_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fanily_members',
            new_name='family_members',
        ),
    ]
