# Generated by Django 4.2.4 on 2023-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_data',
            field=models.BooleanField(default=False),
        ),
    ]
