# Generated by Django 4.1.3 on 2023-02-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='default', max_length=128, verbose_name='password'),
        ),
    ]
