# Generated by Django 4.1.3 on 2023-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
